<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Support Ticket</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #3498db;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #2c3e50;
            margin: 0;
        }
        .priority {
            display: inline-block;
            padding: 5px 10px;
            border-radius: 3px;
            font-weight: bold;
            font-size: 12px;
            text-transform: uppercase;
        }
        .priority-low { background-color: #d4edda; color: #155724; }
        .priority-medium { background-color: #fff3cd; color: #856404; }
        .priority-high { background-color: #f8d7da; color: #721c24; }
        .priority-urgent { background-color: #dc3545; color: white; }
        .info-section {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin: 15px 0;
        }
        .info-row {
            display: flex;
            margin-bottom: 10px;
        }
        .info-row:last-child {
            margin-bottom: 0;
        }
        .info-label {
            font-weight: bold;
            min-width: 120px;
            color: #2c3e50;
        }
        .message-content {
            background-color: #ecf0f1;
            padding: 20px;
            border-radius: 5px;
            border-left: 4px solid #3498db;
            margin: 20px 0;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ecf0f1;
            color: #7f8c8d;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎫 New Support Ticket</h1>
            <p>Car Wash App Support System</p>
        </div>

        <div class="info-section">
            <div class="info-row">
                <span class="info-label">Priority:</span>
                <span class="priority priority-{{ $priority }}">{{ ucfirst($priority) }}</span>
            </div>
            <div class="info-row">
                <span class="info-label">Subject:</span>
                <span>{{ $subject }}</span>
            </div>
            <div class="info-row">
                <span class="info-label">From:</span>
                <span>{{ $name }} ({{ $email }})</span>
            </div>
            <div class="info-row">
                <span class="info-label">Submitted:</span>
                <span>{{ $submitted_at->format('F d, Y \a\t g:i A') }}</span>
            </div>
            <div class="info-row">
                <span class="info-label">IP Address:</span>
                <span>{{ $ip_address }}</span>
            </div>
        </div>

        <div class="message-content">
            <h3>Message:</h3>
            <p>{{ $message }}</p>
        </div>

        <div class="info-section">
            <h4>Technical Information:</h4>
            <div class="info-row">
                <span class="info-label">User Agent:</span>
                <span style="font-family: monospace; font-size: 12px;">{{ $user_agent }}</span>
            </div>
        </div>

        <div class="footer">
            <p>This support ticket was automatically generated by the Car Wash App support system.</p>
            <p>Please respond to this ticket within 24 hours during business hours.</p>
        </div>
    </div>
</body>
</html> 